# Generated by Django 4.2.7 on 2023-12-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christmas_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='christmasmessage',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='christmasmessage',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
